name: CI
on: [push]

jobs:
  sast_bandit_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository 
      uses: actions/checkout@v4.1.1

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.9'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.1.0
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  sast_bearer_scan:
    name: Run Bearer Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository 
      uses: actions/checkout@v4.1.1

    - name: Run Bearer Scan
      uses: bearer/bearer-action@v2
      with:
        severity: critical,high
        format: sarif
        output: bearer-results.sarif
    
  sonarqube_scan:
    name: Run Sonar Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository 
      uses: actions/checkout@v4.1.1

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.0.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
    # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL

    # Optionally you can use the output from the Quality Gate in another step.
    # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
    - name: "Example show SonarQube Quality Gate Status value"
      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
  
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository 
      uses: actions/checkout@v4.1.1
      
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'
      
    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    # - name: Docker Scout Scan
    #   run: |
    #    curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
    #    sh install-scout.sh
    #    echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    #    docker scout quickview
    #    docker scout cves

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.2.2
      with:
       dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
       dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
       command: quickview,cves
       only-severities: critical,high
       sarif-file: scout-report.sarif

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.1.0
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif
